website:
  host: http://www.abc.com
  title: 测试标题

logging:
  encoding: console
  filename: asdf
  filepath: E:/Log

db:
  xhminc:
    driverName: mysql
    host: localhost
    port: 3306
    username: root
    password: 123456
    dbname: xhminc
    charset: utf8mb4
    parseTime: true
    loc: UTC
    timeout: 30s
    readTimeout: 30s
    writeTimeout: 30s
    rejectReadOnly: false
    checkConnectionLiveness: true
    maxIdleConnections: 2
    maxOpenConnections: 2
    connectionMaxLifetime: 30s
  tradercat:
    driverName: mysql
    host: localhost
    port: 3306
    username: root
    password: 987654321
    dbname: tradercat
    charset: utf8mb4
    parseTime: true
    loc: UTC
    timeout: 30s
    readTimeout: 30s
    writeTimeout: 30s
    rejectReadOnly: false
    checkConnectionLiveness: true
    maxIdleConnections: 2
    maxOpenConnections: 2
    connectionMaxLifetime: 30s


