server:
  addr: :40000

application:
  session:
    jwt:
      timeout: 10s
      method: HS256
    cookie:
      enable: false
      name: sessionid
      path: /
      timeout: 10h
      domain: tradercat.xhm-inc.com
      httpOnly: true

website:
  host: http://www.abc.com
  title: 测试标题

logging:
  encoding: console
  filename: dev
  filepath: d:/Log

db:
  xhminc:
    driverName: mysql
    host: localhost
    port: 3306
    username: ENC(9cfab5b8abbef0cc)
    password: 123456
    dbname: xhminc
    charset: utf8mb4
    parseTime: true
    loc: UTC
    timeout: 30s
    readTimeout: 30s
    writeTimeout: 30s
    rejectReadOnly: false
    maxIdleConnections: 2
    maxOpenConnections: 2
    connectionMaxLifetime: 30s
  tradercat:
    driverName: mysql
    host: localhost
    port: 3306
    username: root
    password: 123456
    dbname: tradercat
    charset: utf8mb4
    parseTime: true
    loc: UTC
    timeout: 30s
    readTimeout: 30s
    writeTimeout: 30s
    rejectReadOnly: false
    maxIdleConnections: 2
    maxOpenConnections: 2
    connectionMaxLifetime: 30s


